Cleanup

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # This will create the filesystem for Java and deploy the JVM
-set -e            # fail fast
+# set -e            # fail fast
 set -o pipefail   # do not ignore exit codes when piping output
 # set -x          # enable debugging
 
@@ -13,6 +13,8 @@ echo "Build Dir is " ${build_dir}
 echo "Cache Dir is " ${cache_dir}
 
 echo "Extracting JVM...."
-tar -xvf resources/jdk.tar.gz -C ${build_dir}
+tar -xvf resources/jre-8u91-linux-x64.tar.gz -C ${build_dir}
 echo mv ${build_dir}/jre* /home/vcap/app/
-mv ${build_dir}/jre* /home/vcap/app/
+# mv ${build_dir}/jre* /home/vcap/app/
+echo BuildDir =
+ls -l ${build_dir}
